/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlab212;

import java.awt.ComponentOrientation;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.ScrollPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ProgressBar;
import javax.accessibility.AccessibleContext;
import javax.swing.BoundedRangeModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/**
 *
 * @author EmreKARA
 */
public class SystemInterface extends javax.swing.JFrame {

    /**
     * Creates new form SystemInterface
     */
    HashMap<String, myProgressBar> progressBars;

    public SystemInterface(HashMap progressBars) throws InterruptedException {
        this.progressBars = progressBars;
        initComponents();
        run();
    }

    public SystemInterface() throws InterruptedException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yazlab 12");
        setResizable(false);

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SystemInterface().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(SystemInterface.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    public void run() throws InterruptedException {
        jPanelMain.setLayout(new GridLayout(4,2,10,10));
        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        //jPanelMain.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        /*JLabel label1 = new JLabel("label1");
        label1.setName("label1");
        JLabel label2 = new JLabel("label2");
        label2.setName("label2");
        JLabel label3 = new JLabel("label3");
        label3.setName("label3");
        jPanelMain.add(label1);
        jPanelMain.add(label2);
        jPanelMain.add(label3);
        myProgressBar pb1 = new myProgressBar("Thread01");
        pb1.set4152(0);
        jPanelMain.add(pb1);
        JLabel label4 = new JLabel("label4");
        label3.setName("label4");
        jPanelMain.add(label4);
        for (int i = 0; i < jPanelMain.getComponents().length; i++) {
            System.out.println("comp: " + jPanelMain.getComponents()[i].getName());
        }
        System.out.println("Ben GELdİMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");*/
        Timer timer = null;

        ActionListener listener = new ActionListener() {
            int counter = 0;
            public void actionPerformed(ActionEvent ae) {
                jPanelMain.removeAll();
                Iterator pbIterator = progressBars.entrySet().iterator();
                while (pbIterator.hasNext()) {
                    Map.Entry mapElement = (Map.Entry) pbIterator.next();
                    jPanelMain.add(((myProgressBar) mapElement.getValue()));
                }
                counter = jPanelMain.getComponentCount();
                //jPanelMain.setLayout(new GridLayout(counter/4,4,10,10));
                ((GridLayout)jPanelMain.getLayout()).setColumns(2);
                ((GridLayout)jPanelMain.getLayout()).setRows((counter/2)+1);
                revalidate();
                repaint();
            }
        };
        timer = new Timer(1100, listener);
        timer.start();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

class myProgressBar extends JProgressBar {

    public myProgressBar(String name) {
        setName(name);
        Font font = getFont();
        font = font.deriveFont(Font.BOLD, 18);
        setFont(font);
        setStringPainted(true);
    }

    public void set4152(int value) {
        setValue(value);
        setString(getName() + ": " + value + "%");

    }

}
